### ISSUE TITLE
"old search" option missing when extension used with TorBrowser

### ISSUE THREAD

**Issue by y** [Aris-t2/ClassicThemeRestorer#196]
Using the latest stable TorBrowser, 5.5.5 (based on Mozilla Firefox 38.8.0), and installed latest version of Classic Theme Restorer (1.5.0), the "Old search" option is missing from the General UI (1) pane.

**Comment by Aris-t2** [comment]
It is "missing", because Firefox 38 (which TorBrowser is based on) offered the old search through an own default about:config switch (browser.search.showOneOffButtons). It got removed in Firefox 43. You can find the browser.search.showOneOffButtons switch on CTRs "Advanced" category when using CTR with Firefox 38.
