### ISSUE TITLE
1.5.2beta5  xpi/locale/en-US/options.dtd

### ISSUE THREAD

**Issue by kkmGH** [Aris-t2/ClassicThemeRestorer#205]
line 248 
"chrome page" has changed "'about:' pages".
What is "'about:' pages"?

**Comment by Aris-t2** [comment]
"about:" pages are browsers own (configuration/info etc.) sites. You can see the overview, if you write "about:about" into your address bar.
I previously called them "chrome" sites, because of their internal path "chrome://path_to_file/file", but "about:" sites is more accurate and understandable for most users.

**Comment by kkmGH** [comment]
thanks
