### ISSUE TITLE
In "Toolbars", When icons & text is chosen, extension will not remember the preference

### ISSUE THREAD

**Issue by SCV91355** [Aris-t2/ClassicThemeRestorer#274]
In "Toolbars", When Icons & Text is chosen, extension will not remember the preference. 

Successive opening of Firefox returns to icons only.

**Comment by Aris-t2** [comment]
I can not confirm that. All "Show icons and text" preference variations work fine for me on all my test scenarios and systems. Which one specifically does not work for you? CTR offers multiple of them and do the others work?

Can you tell me more about your setup (OS, OS version, add-ons, Firefox version).

Make sure also to run your tests on a clean new browser profile with only CTR installed to verify this issue is not being caused by another add-on or a broken browser profile.

**Comment by SCV91355** [comment]
Sorry for the delay. First, thanks for your good work with this extension.

 

I do not have any other extensions interfering with your extension, and after experimenting, I can only make this work

by using the “experimental” mode=full. Again, after much “fiddling”, the choices at the top of the mode list, will not work.

 

Dave

**Comment by Aris-t2** [comment]
Have you tried creating a new browser profile and only installing CTR? You may not be aware of a broken browser profile or other add-ons settings/leftovers, that can interfere.

You still have not told anything about your setup (OS, OS version, add-ons, themes, Firefox version)

If you are using Windows, try to setup Portable Firefox and only install CTR.

**Comment by SCV91355** [comment]
I’ll work on your suggestions. Thanks. This box is running Windows 7. I have another newly built desktop running Win 10, and will try on that.

 

I’ll need to experiment with a new Firefox browser profile. Firefox is running 48.0.2. I only manually update. Extensions are:



 

Many Thanks….
