### ISSUE TITLE
Firefox preset

### ISSUE THREAD

**Issue by trup** [Aris-t2/ClassicThemeRestorer#317]
when I select "Firefox preset", not all settings are reset, eg " 'Download notification' animation" is not reset to the default value.

**Comment by Aris-t2** [comment]
CTR does not reset, restore, export or import default browser preferences, only its own. Every option with a "about:config >> ..." description below it gets ignored by those settings on purpose.
It is not a bug but a design decision to avoid security issues, when it comes to changing default browser preferences through an add-on.

Providing a switch for default about:config preferences is not determined as a potential thread by "Mozillas add-on validator", because changes are done manually by user and not by add-on or one of its features automatically.
