### ISSUE TITLE
Bug: "Alternative appearance" in add-ons is enabled by default

### ISSUE THREAD

**Issue by vitaliylag** [Aris-t2/ClassicThemeRestorer#337]
"Alternative appearance" in add-ons should not be enabled by default. Also alternative appearance looks much worse.

Ideally the extension should not change anything without user permission because user cannot know what have been changed after installing the extension and what options he need to change to restore it back.

Some auto-changes are acceptable. For example auto-changing tabs style and adding Firefox button is acceptable because there is no way user will not notice this. After noticing user can restore it back if he don't like it. But even in this case I would opened tutorial with screenshot instead: after seeing screenshots user can change Firefox button by himself.

Also "Cancel all changes" option in settings is also acceptable. With this option the extension can change anything after installing but if user want to set all options by himself he cancel all changes made by the extension and set the options from zero.

**Comment by Aris-t2** [comment]
I think you saw the end of these type of extensions it quite near (Fx57+), so because of that I have no plans to make any big changes to CTR or my other add-ons anymore.

It is debatable what looks good or bad, but some features were chosen to be "active by default" to show users some instant changes after installing this add-on. After all users have to see more than two changes (titlebar buttons, tab) after installing CTR.

Reverting the currently active by default option "Alternative appearance" on next update would only confuse old/current users, because they would need to reset that option again.

CTR provides a preset where most CTR settings get disabled (prefwindow > settings > Firefox preset). Users can "start" configuring CTR from scratch after using it.

I agree a custom guide how to do/undo settings, a proper user handbook for every options etc. would be very helpful, but it is very time consuming to create and I won't add it, because CTR almost reached EOF (end of life) state (see https://github.com/Aris-t2/ClassicThemeRestorer/issues/299).

**Comment by vitaliylag** [comment]
Thanks, I didn't see "Firefox preset". In russian "profiles" are called "settings" so I didn't even click that button.

**Comment by Aris-t2** [comment]
"profiles" > "профили" (nothing for "profiles" in CTR anyway)
"settings" > "настройки"
"preset(s)" > "предустановки"
