### ISSUE TITLE
Firefox Titlebar and OS Titlebar are showing up on different rows

### ISSUE THREAD

**Issue by ajaygupta10** [Aris-t2/ClassicThemeRestorer#350]
Nightly 56.a01 (6/19/2017)  - Win 64bit version
CLT Beta 1.6.8Beta1

**Comment by Aris-t2** [comment]
Can't confirm that.

Win7 - OS titlebar / Fx titlebar
![1](https://user-images.githubusercontent.com/6013569/27297520-6af134d4-5525-11e7-9019-ac75abd72919.png)

Win10 - OS titlebar / Fx titlebar
![2](https://user-images.githubusercontent.com/6013569/27297523-6f0f5122-5525-11e7-8058-3ef1b1258498.png)

**Comment by ajaygupta10** [comment]
This is what I see:

[image: Inline image 1]

Forgot to add that I am running Windows 10 Insider Preview 16199. I would
like to conjecture that Windows Preview Version may not be an issue since
this problem just started a few days back and I am on this Preview for two
weeks or so.

*Ajay Gupta*
ajaygupta10@gmail.com
+1-630-344-9099

**Comment by Aris-t2** [comment]
Sorry, I don't see any image, just this text

"[image: Inline image 1]"

Have you attached it to your post? Try http://imgur.com/ instead.

I saw some recent changes in Nightly on Windows 10. Most likely they are responsible for a lot of things since Photon changes keep landing on Nightly. I suggest to switch to Firefox 52 ESR, if you want a working CTR for a while.

**Comment by ajaygupta10** [comment]
Thanks for your investigation of this. I am trying again to attach the
image (still via gmail route). I will try the imgur route if this fails as
well.

Since Firefox would soon make it impossible to have CTR, I guess I will
have to console myself that I will just have to live with Firefox standard
Appearance.

*Ajay Gupta*
ajaygupta10@gmail.com
+1-630-344-9099

**Comment by Aris-t2** [comment]
You actually do not need any image host for your screenshot. Just drag and drop the image into your post here and it will be uploaded to Github automatically. You can insert it above or below any text your write here.

Anyway, test 1.6.8 beta 2. I had to change some things for the application button in titlebar. Maybe that was you issue.

Mozilla has added some css code on a level CTR can not override properly, because the code is dynamically changed. Therefore Fx56 on Windows 10 now has the appbutton on the same level as tabs, because that is what Mozilla forces tabs to be (in titlebar).

**Comment by ajaygupta10** [comment]
Yup. The CTR is working fine now. Thanks.

*Ajay Gupta*
ajaygupta10@gmail.com
+1-630-344-9099
