### ISSUE TITLE
CSS conflict with Tile Tabs

### ISSUE THREAD

**Issue by Imold** [Aris-t2/ClassicThemeRestorer#47]
ClassicThemeRestorer messes up the button for Tile Tabs, when it's on the navbar.
The problem is in smallnavbutextra.css.
```
    #navigator-toolbox #nav-bar #back-button[disabled] > .toolbarbutton-icon,
	#navigator-toolbox #nav-bar .toolbarbutton-menubutton-dropmarker > image,
	#navigator-toolbox #nav-bar .toolbarbutton-menubutton-button .toolbarbutton-icon,
	#navigator-toolbox #nav-bar toolbarbutton[type="menu-button"] > .toolbarbutton-icon,
	#navigator-toolbox #nav-bar .toolbarbutton-1:-moz-any(:hover ,[checked],[open],[type="menu-button"]) > .toolbarbutton-icon,
	#navigator-toolbox #nav-bar .toolbarbutton-1[type="menu-button"] > .toolbarbutton-menubutton-dropmarker::before{
	  -moz-appearance: none !important;
	  background: none !important;
	  background-image: none !important;
	  border-radius: 2.5px;
	  border-color: transparent !important;
	  box-shadow: none !important;
	  transition-property: none !important;
      transition-duration: 0ms !important;
	} 
```
needs to be changed to
```
    #navigator-toolbox #nav-bar #back-button[disabled] > .toolbarbutton-icon,
	#navigator-toolbox #nav-bar .toolbarbutton-menubutton-dropmarker > image,
	#navigator-toolbox #nav-bar .toolbarbutton-menubutton-button .toolbarbutton-icon,
	#navigator-toolbox #nav-bar toolbarbutton[type="menu-button"] > .toolbarbutton-icon,
	#navigator-toolbox #nav-bar .toolbarbutton-1:-moz-any(:hover ,[checked],[open],[type="menu-button"]) > .toolbarbutton-icon,
	#navigator-toolbox #nav-bar .toolbarbutton-1[type="menu-button"] > .toolbarbutton-menubutton-dropmarker::before{
	  -moz-appearance: none !important;
	  background: none;
	  background-image: none !important;
	  border-radius: 2.5px;
	  border-color: transparent !important;
	  box-shadow: none !important;
	  transition-property: none !important;
      transition-duration: 0ms !important;
	} 
```
The "!important" on "background: none" needs to be removed to fix the problem with the button for Tile Tabs. Right now I've moved every thing to another toolbar and hidden the navbar but it's a pain when I install a new addon and the toolbar button goes right to the navbar.

**Comment by Aris-t2** [comment]
Fixing one button of one add-on like this will break all other add-ons, that provide menu-buttons.

Tile tabs does a couple of ugly things to the ui such as (non-optionally) modifing tabs toolbar and tabs with a ugly line below active tabs as result (most tab settings) and ugly non-disappearing tab separators, if using default tabs.

It also unnecessarily modifies toolbar buttons padding/margins and icon appearance via icon background color instead of using different icons for different button states.

Unfortunately Tile tabs does not provide any button ids for its toolbars buttons "sub buttons", so I can't even exclude them from the code.

Some ideas how to fix this kind of problems on Tile tabs side:
1. Adding toolbar button id for sub-button, so other add-ons can exclude code for it.
or
2. Use colorized icons for every state instead of modifying icons/buttons background colors.
or
3. Colorizing icons background using more powerful nodes like this

```css
#main-window #navigator-toolbox #nav-bar #tiletabs-buttonmenu .toolbarbutton-menubutton-button image {
  background-color: grey !important;
 }
```
'grey' is just an example in this case to show, how this add-on could/should set/override colors.
