### ISSUE TITLE
appbutton and titlebar-button height is increased and affect complete theme

### ISSUE THREAD

**Issue by magicp-github** [Aris-t2/ClassicThemeRestorer#73]
Hi Aris,

I raise an issue as follows...

appbutton and titlebar-button height is increased and affect complete themes. Please refer to the attached image. CTR 1.3.6 or 1.3.7.1 is better for me. Could you investigate this issue? Thank you in advance.

My environment:
- Windows 10 (64-bit)
- Firefox 40.0.2 (32 bit)
- Qute 5++ 1.5.6

Regards,
magicp

![classic-theme-restorer](https://cloud.githubusercontent.com/assets/13914314/9422908/e63e7ff6-48e4-11e5-8296-76e1a367104f.png)

**Comment by Aris-t2** [comment]
This will be fixed on next beta.

**Comment by magicp-github** [comment]
I confirmed 1.3.8beta2. Unfortunately, it's degrade. Please refer to the attached image. I know you are busy. If you are difficult to fix for both themes, please fix for default theme firstly. I will be able to adjust from default theme.

I am awaiting next version.

Thanks,
magicp

![classic-theme-restorer-1 3 9beta2](https://cloud.githubusercontent.com/assets/13914314/9454864/509d47de-4b00-11e5-8605-c499d035cc80.png)

**Comment by Aris-t2** [comment]
Hi,
I know the caption icons are not vertically centered when you hover them, but this is done for a few reasons atm:
1. The icons stay on their supposed position.
2. The application button looks almost like on Win7/8.
3. There is no huge gap between titlebar and tabs toolbar, which would be there, because Firefox titlebar on Windows 10 has a different height compared to older Windows builds.
4. Caption buttons do not overlay with tabs below them.

I will tweak the code a bit for next beta hopefully without breaking the ui for some other cases.

After switching 'appbutton on titlebar' to on or off, you always have to resize your window for top toolbar area being correctly displayed again. (maximize/minimize window)

**Comment by magicp-github** [comment]
Hi Aris,

Thanks new beta.
I confirmed 1.3.8beta3 and beta4, and issue was fixed. Qute 5++/6++ 1.5.7beta1 will adjust caption icon position. I appreciate your excellent work.

Regards,
magicp
